---
name: Pull Request Build, Tag, & Push
on:
  pull_request:
    branches:
      - develop
      - main
      - master
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  build-develop-open:
    if: github.base_ref == 'develop' && github.event.pull_request.merged == false
    uses: kbaseincubator/.github/.github/workflows/reusable_build.yml@main
    with:
      platforms: "linux/amd64"
    secrets: inherit
  build-develop-merge:
    if: github.base_ref == 'develop' && github.event.pull_request.merged == true
    uses: kbaseincubator/.github/.github/workflows/reusable_build-push.yml@main
    with:
      name: '${{ github.event.repository.name }}-develop'
      tags: pr-${{ github.event.number }},latest
      platforms: "linux/amd64"
    secrets: inherit
  build-main-open:
    if: (github.base_ref == 'main' || github.base_ref == 'master') && github.event.pull_request.merged == false
    uses: kbaseincubator/.github/.github/workflows/reusable_build-push.yml@main
    with:
      name: '${{ github.event.repository.name }}'
      tags: pr-${{ github.event.number }}
      platforms: "linux/amd64"
    secrets: inherit
  build-main-merge:
    if: (github.base_ref == 'main' || github.base_ref == 'master') && github.event.pull_request.merged == true
    uses: kbaseincubator/.github/.github/workflows/reusable_build-push.yml@main
    with:
      name: '${{ github.event.repository.name }}'
      tags: pr-${{ github.event.number }},latest-rc
      platforms: "linux/amd64"
    secrets: inherit
  trivy-scans:
    if: (github.base_ref == 'develop' || github.base_ref == 'main' || github.base_ref == 'master' ) && github.event.pull_request.merged == false
    uses: kbaseincubator/.github/.github/workflows/reusable_trivy-scans.yml@main
    secrets: inherit
